[package]
name = "cbs-dependent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbs-dependency = { git = "https://github.com/joao-paulo-parity/cbs-dependency", branch = "master" }
